const mongoose = require('mongoose');

// _id: 5e059a07c4443b03c4ee8a93
// Total = 24 chars
// Every 2 chars represent 1 byte

// 12 bytes 
    // 4 bytes: timestamp
    // 3 bytes: machine identifier
    // 2 bytes: process identifier
    // 3 bytes: counter

// 1 byte = 8 bits
// 2 ^ 8 = 256
// 2 ^ 24 = 16M (counter)

// _id is generated by Driver that talks -> MongoDB
// that's why applications built on mongodb are highly scalable.

const id = new mongoose.Types.ObjectId();
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid('1234');
console.log(isValid);